config/routes.rb
SampleApp::Application.routes.draw do
  resources :users

  match '/', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'  
  match '/signup',    :to => 'users#new'  

  root :to => 'pages#home'
  

end

app/models/user.rb
# == Schema Information
# Schema version: 20110215155800
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :encrypted_password
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length   => { :maximum => 50 }

  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  # Static method of the class
  def self.authenticate(email, submitted_password)
    user = User.find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  # --------------
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'Home'
  end

  def contact
    @title = 'Contact'
  end
  
  def about
    @title = 'About'
  end
  
  def help
    @title = 'Help'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign Up"
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def create
    @user = User.new(params[:user])
    if (@user.save)
      flash[:success] = "Your account was successfuly created!"
      redirect_to @user
    else
      @title = "Sign Up"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on per page basis
  def title
    base_title = 'Ruby on Rails Sample App'
    if @title.nil?    
      base_title
    else
      "#{base_title} | #{@title}" 
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 50 } )
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => "gravatar",
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.haml
%footer
	%hr/
	%nav.round
		%ul
			%li= link_to "About", about_path
			%li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
%header
	- logo = image_tag("logo.png", :alt => "Sample App", :class => "round")
	= link_to logo, root_path
	%nav.round
		%ul
			%li= link_to "Home", root_path
			%li= link_to "Help", help_path
			%li= link_to "Sign Up", signup_path

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'compiled/screen.css', :media => 'screen'
= stylesheet_link_tag 'compiled/print.css', :media => 'print'
/[if IE]
	= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/custom.css', :media => 'screen'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= title
		= csrf_meta_tag
		= render 'layouts/stylesheets'
	%body.two-col.bp
		#container
			= render 'layouts/header'
			%aside#sidebar
				- if @title == "Home"
					%h4 Users
					- User.all.each do |user|	
						%ul.userList
							%li= link_to user.name, user_path(user)
				- else
					&nbsp;
			%section#content
				- flash.each do |key, value|
					%div{:class => "flash #{key}"}= value
				= yield
				= debug(params) if Rails.env.development?
			=render 'layouts/footer'

app/views/pages/about.html.haml
%h1= "About Page"
%p 
	="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	You can visit the
	%a(href ='#' title = title)= @title
	page to see more details

app/views/pages/contact.html.haml
%h1= "Contact Page"
%p 
	="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	%a(href ='#' title = @title)= @title

app/views/pages/help.html.haml
%h1= "Help"
%p 
	:markdown
		Get help on Ruby on Rails Tutorial at the [Rails Tutorial help page](http://railstutorial.org/help)  
		To get help on this sample app, see the	[Rails Tutorial book](http://railstutorial.org/book).

app/views/pages/home.html.haml
%h1= "Home Page"
%p 
	="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	%a(href ='#' title = @title)= @title
	%br/
	= link_to "Sign up now!", signup_path, :class => "signup_button", :title => "Sign up"

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
	#error_explanation
		%h2
			= pluralize(@user.errors.count, "error")
			prohibited this user from being saved:
		%p There were problems with the following fields:
		%ul
			- @user.errors.full_messages.each do |msg|
				%li= msg
%br/				

app/views/users/new.html.haml
%h1 Sign Up

= form_for(@user) do |f|
	= render 'shared/error_messages'
	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :email
		= f.text_field :email
	.field
		= f.label :password
		= f.password_field :password
	.field
		= f.label :password_confirmation, "Confirmation"
		= f.password_field :password_confirmation
	.actions
		= f.submit "Sign up"

app/views/users/show.html.haml
%h1
	= gravatar_for @user, :size => 50
	= @user.name

%ul.form
	%li
		%span.label Name
		%span.value= link_to @user.name, user_path(@user)
	%li
		%span.label Email
		%span.value= @user.email